# Generated by Django 3.2.12 on 2022-05-06 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='owner',
            new_name='author',
        ),
    ]
